# Generated by Django 3.2 on 2023-05-03 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Год выпуска должен быть больше 0'), django.core.validators.MaxValueValidator(2023, message='Год выпуска должен быть не больше текущего')], verbose_name='Год выпуска'),
        ),
    ]
